apiVersion: apps/v1
kind: Deployment
metadata:
  name: rambuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rambuggy
  template:
    metadata:
      labels:
        app: rambuggy
    spec:
      containers:
      - name: rambuggy
        image: 261399255188.dkr.ecr.ap-south-1.amazonaws.com/ram_devsecops
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rambuggy
    k8s-app: rambuggy
  name: rambuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: rambuggy
