pipeline {
  agent any
  tools { 
        maven 'Maven_3.8.4'  
    }
   stages{
    stage('CompileandRunSonarAnalysis') {
            steps{
				dir('devsecops-jenkins-k8s-tf-sast-sca-sonarcloud-snyk-repo') {	
		sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=ram-gs -Dsonar.organization=ram-gs -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=56cd3f47c2ec02f10c59b6aed4f556c1f46f6774'
			}
    }}

	stage('RunSCAAnalysisUsingSnyk') {
            steps {	
				dir('devsecops-jenkins-k8s-tf-sast-sca-sonarcloud-snyk-repo') {
				withCredentials([string(credentialsId: 'SNYK_TOKEN', variable: 'SNYK_TOKEN')]) {
					sh 'mvn snyk:test -fn'
				}
			}}
    }
	 stage('Build') { 
            steps { 
            dir('devsecops-jenkins-k8s-tf-sast-sca-sonarcloud-snyk-repo'){
               withDockerRegistry([credentialsId: "dockerlogin", url: ""]) {
                 script{
                 app =  docker.build("ramgsdso")
                 }
               }
            }}
    }

	stage('Push') {
            steps {
                 dir('devsecops-jenkins-k8s-tf-sast-sca-sonarcloud-snyk-repo'){

                script{
					
                    docker.withRegistry('https://261399255188.dkr.ecr.ap-south-1.amazonaws.com', 'ecr.ap-south-1:aws-credentials') {
                    app.push("latest")
                    }
                }
            }}
    	}
  }
}
